services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sales
      POSTGRES_PASSWORD: sales
      POSTGRES_DB: sales_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sales -d sales_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ..
      dockerfile: services/user-service/Dockerfile
    container_name: sales-sync-user-service
    environment:
      CONFIG_PATH: /config/local.yaml
      MIGRATIONS_PATH: /app/db/migrations
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - ./config:/config
      - ../services/user-service/db/migrations:/app/db/migrations

volumes:
  postgres_data:


